### ISSUE TITLE
Can't download the public dataset 

### ISSUE THREAD

**Issue by Michael95-m** [sberbank-ai/StackMix-OCR#25]
I can't download the public datset by running the following command
```
python3.9 scripts/download_dataset.py --dataset_name=peter
```

The following error can be found by running download_dataset.py script
```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1zjloEBbIBZkw4zrpYn3YrGuPHXep-xOk
```

I think the script will surely work by changing the permission to 'Anyone with the link. Thanks

**Comment by shonenkov** [comment]
@Michael95-m due to sanctions against russia, microsoft/google deleted academic accounts of researchers and even some non-profit projects - sorry, but I dont imagine how I can restore data from google drive

**Comment by skalinin** [comment]
You can download Peter dataset from hugging face https://huggingface.co/datasets/sberbank-ai/Peter
